name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Node Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Formatting
        run: npm run format:check

      - name: Unit tests
        run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.5
        with:
          image: yougo-ui
          dockerfiles: Dockerfile

      - name: Publish Image to GitHub Packages
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.pkg.github.com/yougo-app/yougo-ui
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_TOKEN }}
